FAULT TYPE: OPENSTACK_THROW_EXCEPTION-INSTANCE
TARGET COMPONENT: /nova/compute/manager.py
TARGET CLASS: ComputeManager
TARGET FUNCTION DEF: _query_driver_power_state_and_sync+6553;12
FAULT POINT: self._sync_instance_power_state(context, db_instance, vm_power_state, use_slave=True)
