FAULT TYPE: OPENSTACK_THROW_EXCEPTION-INSTANCE
TARGET COMPONENT: /nova/compute/manager.py
TARGET CLASS: ComputeManager
TARGET FUNCTION DEF: None+3155;8
FAULT POINT: self._notify_about_instance_usage(context, instance, 'reboot.end')
