FAULT TYPE: OPENSTACK_THROW_EXCEPTION-VOLUME
TARGET COMPONENT: /nova/compute/api.py
TARGET CLASS: API
TARGET FUNCTION DEF: _check_attach_and_reserve_volume+3737;8
FAULT POINT: self.volume_api.reserve_volume(context, volume_id)
