FAULT TYPE: OPENSTACK_THROW_EXCEPTION-INSTANCE
TARGET COMPONENT: /nova/compute/manager.py
TARGET CLASS: ComputeManager
TARGET FUNCTION DEF: external_instance_event+7082;20
FAULT POINT: self.network_api.get_instance_nw_info(context, instance)
