FAULT TYPE: OPENSTACK_THROW_EXCEPTION-VOLUME
TARGET COMPONENT: /cinder/volume/manager.py
TARGET CLASS: VolumeManager
TARGET FUNCTION DEF: attach_volume+1181;8
FAULT POINT: self._notify_about_volume_usage(context, volume, 'attach.start')
