FAULT TYPE: OPENSTACK_THROW_EXCEPTION-INSTANCE
TARGET COMPONENT: /nova/compute/resource_tracker.py
TARGET CLASS: ResourceTracker
TARGET FUNCTION DEF: _update_usage_from_instance+1096;16
FAULT POINT: self.pci_tracker.update_pci_for_instance(context, instance, sign=sign)
