FAULT TYPE: OPENSTACK_THROW_EXCEPTION-INSTANCE
TARGET COMPONENT: /nova/compute/manager.py
TARGET CLASS: ComputeManager
TARGET FUNCTION DEF: _sync_scheduler_instance_info+1657;8
FAULT POINT: self.scheduler_client.sync_instance_info(context, self.host, uuids)
