FAULT TYPE: OPENSTACK_THROW_EXCEPTION-NETWORK
TARGET COMPONENT: /nova/api/openstack/compute/servers.py
TARGET CLASS: ServersController
TARGET FUNCTION DEF: _get_requested_networks+422;20
FAULT POINT: self._validate_network_id(request.network_id, network_uuids)
