FAULT TYPE: OPENSTACK_THROW_EXCEPTION-VOLUME
TARGET COMPONENT: /nova/compute/manager.py
TARGET CLASS: ComputeManager
TARGET FUNCTION DEF: _attach_volume+4925;8
FAULT POINT: compute_utils.notify_about_volume_attach_detach(context, instance, self.host, action=fields.NotificationAction.VOLUME_ATTACH, phase=fields.NotificationPhase.START, volume_id=bdm.volume_id)
