FAULT TYPE: OPENSTACK_THROW_EXCEPTION-VOLUME
TARGET COMPONENT: /nova/compute/api.py
TARGET CLASS: API
TARGET FUNCTION DEF: _attach_volume+3752;12
FAULT POINT: self._check_attach_and_reserve_volume(context, volume_id, instance)
