FAULT TYPE: OPENSTACK_THROW_EXCEPTION-INSTANCE
TARGET COMPONENT: /nova/compute/api.py
TARGET CLASS: API
TARGET FUNCTION DEF: external_instance_event+4344;12
FAULT POINT: self.compute_rpcapi.external_instance_event(cell_context, instances_by_host[host], events_by_host[host], host=host)
